In [1]:
import numpy as np

In [2]:
X_train=np.array([[1,2,3],
                 [4,5,6],
                  [7,8,9]])

In [3]:
X_train

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
from sklearn import preprocessing

In [7]:
X_scale=preprocessing.scale(X_train)
## uses standard scale being mean=0 making variance to be 1

In [10]:
X_scale.mean(axis=0)

array([0., 0., 0.])

In [13]:
X_scale.std(axis=0)

array([1., 1., 1.])

In [15]:
#problem with X_scale is that if we want to scale any data then we have to combine x_train and x_test data 
# but generally we don't have the test data 
# if we scale speratelly then both data are scaled using differnt way  that will lead to hug problem in classification or regression
# we want that we have x_train data we will scale that data and store the scaling parameters 
#then whenever we scale test data we use those stored parameter in it

In [16]:
scaler=preprocessing.StandardScaler()

In [17]:
scaler.fit(X_train)

StandardScaler()

In [21]:
scaler.transform(X_train)

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

In [26]:
X_test=[[1,2,3]]

In [27]:
scaler.transform(X_test)

array([[-1.22474487, -1.22474487, -1.22474487]])